language: java
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
env:
  matrix:
  - TERM=dumb
  global:
  - secure: lpbKShEFl478I5YuhYmhHlv03upni/RUisT0IbnMnUEhaNLXYXmurZZbo2nbI46vURdBx62Pn9m2ein8e9s0igP/DIdEmPDvDfkEOIzzparq8ZKDokhiK5GIRaq9fbOpIZgOC6ZTywqDFlsenNqUqct+YGNDmcbL+8PcbE8EBvHj8zi4l02QsTVKwvmFgAgCzkkcAVBwlZUpwuLzzqTRj5XNY7qdkmcmL6tP/Box7FT3rTEQSUAIMOZ2PG658YobpH0cXNYLkuVW1C17WTe9xFKfvdKm8T0QpsGE04Y3/BUAQ2H9TF7q6I6x2ewWOG4fgdNk1ZV1f71Vxntx2paXByW2JN4g8i+1ylZeJqZCST9joYo9d/0hrQMAR4qMtI+47ekcXrk5jq8Ov8XU5lR6NQ85sPXtv63Yg92lgO1uvpeEjEwT/nv78WAAmOhpg4R6Pa58fl0lzHjQJNTPbEdvPXGtg7RbBL1Qb0l+qOfyCCDYgM5TM4j8oUp4u8PRRs/2wlgP9xF6tGEaID5qxZhpIUa8+OmJG7FRd7hPJ1SsaBDrTLiyDot8ay1e8K39hTJdsg/TsN+NX5KceH//zCxCJt+EvW/m4pYPIUWq9iztlV1v2ZHxfK8re/fasxnq+/tIOsd+c3c8Wj2JB4h7icSPPtrG/lq4YHYv2cA0TVfk+t0=
  - secure: X4Z119tGWnG/Y4uq32wWGZbLv7AtsLwFXlcyOlGi3jyhrx2tqZqcQyKkhQOf/OlHxkOk3F92omW6ZCjdrQUXsoKz8rKZIC0+noobLSzq6vLMmJFajVx6dwcj0ahayrgxqtNbHgIq8TsUbY10vSLOap7anV6pM50qEuNSJkMuLUqSNcgD91bCS4UH0nshrIbUWD7zjiVCHGQaYD2McHlbfHfXbIo1Kn3Nh99wDfPYNAIPF9jX4ht5m8wZ44ZgkAmnUivhGRq0mwcOI8GHglWMhCq0KJYeQVIYYdDPLjrUZHkYna5NKoDcQWIPI2boisEGEA4duE2w/kwJTJ7BQSBFOoLEsm8OEAZhaG+iXNxAieoL45LBIIINh537MwhXM23dDE473GjMuWvM+Hf99/NVlQzodyrSvLFqu+TAJl2aSzNNX0Z/x553RXsceqm7UEoZuUQsczlAfJKV/KXhe06Cf3mQYrMTP4ys1QufEBu1KBJx76LtRyFv8aESXc8sXHY9ZDd+5YyQiKdnYfXHrt3WH+ngUSw6oQlgwTiXTw8HX6u/bAzvgG8TsWYEviigpbLk1eVBspRSoBgfVcSZewZHWtldCr2i/GcBzdS6y1CkeB56xsyaq+2eEeCJ4ElcUBCQ3P8K7G0MdGxHnb8lq9KZsrsYNREe0bukZ8y7WBRB7+0=
  - secure: jMXfuA/X26PwWNXl3I7jl0GvwPhq6CUcK5Bp+Inu0Vg53iRu19GHUop12GursUiRQyyI9kiT7Sd5j4GAVX9TMXwce9e1/4qjxoXnIlVHeRxu8DlbSfw1LE8IiGcrDgx8bBNSflwRIjXiOo3H1H8+ayh4SzQVrpKv5O/5+ciAud9sBSxD81pOLQ1gxKNHf8GktuqBZJ2Htv1YAsgY9FMq00SIjW5+KXGCiibpXiKPc1IYw6CNgta80GrN6LQaS4TEcGrieLZkEJbCMOqUooiUmOSxlN/UxsK+7U7s3M4DA0Lcqt2vGBljvESUEMdv7iy819hJ9xWQMWWyZNCZbZKMiwe7Nt/oQaVRhj/+Usi8/rykrCpYEVHahyTsH5pWA3oFnfvH+94Ln4gcZc5yUeiK2LCPBSy9ibUUa5RtG/ZphypH9Q5Xi9UiGmf20vdzZf2h5mX28agkR92vVDRoiqO05CBZTvnLotjXw1rm1imXIIa7g4mZFHMLyOiTGl7ma61e7quGx01XQ038Sbfo5GR8uqnkwNYFcmgtnKcl83XsJ5Z0O9fNbF3778mSp0xnyBzKddQGA6HaVuJq+NE8U3br6STN9VESWhpgN94xxJvQiLzUG1/h+MtvrM3EOdA5FyK8LIKHVcg3/DVOJCGSPgHabzCIbETSfCdK90/WMpHK0bk=
before_install:
- chmod +x gradlew
install: "./gradlew --version"
script: ./gradlew --continue build test aggregateJavadoc publishGhPages artifactoryPublish
  -PgithubUser="${GITHUB_TOKEN}" -PgithubPassword="" -PjfrogUser="${JFROG_USER}" -PjfrogPassword="${JFROG_PASSWORD}"
  --stacktrace
